Repository cculianu/Fulcrum, pull requests merged in 2020-07, with the labels that each got.

#30 Fixups and optimizations to JSON Parsing + set all locale APIs to "C"
  src/App.cpp
  src/Json.cpp
  src/Json_Parser.cpp
  test/json/fail1.json
  test/json/fail53.json
  test/json/pass8.json
  test/json/round1.json
  test/json/round9.json
Labels: correctness, performance

#38 ServerSSL: Do not request client certificates from clients
  src/Servers.cpp
Labels: bug

#37 WebSocket: Correctly handle multiple values in the Connection header
  src/WebSocket.cpp
  src/WebSocket.h
Labels: bug, websocket

#39 WebSocket: flush socket before exception to make errors reliable
  src/WebSocket.cpp
Labels: correctness, websocket

#40 Use rocksdb package for RPM build
  contrib/rpm/fulcrum.spec
Labels: packaging
