Repository cculianu/Fulcrum, pull requests merged in 2020-08, with the labels that each got.

#48 Travis: Build and run tests
  contrib/travis/linux.ubuntu.script
  contrib/travis/osx.mac.script
  contrib/travis/windows.pc.script
Labels: CI and Tests

#49 Build: Allow build against system rocksdb on Windows
  Fulcrum.pro
Labels: building

#51 Docker: Preload jemalloc to reduce heap fragmentation
  contrib/docker/Dockerfile
Labels: packaging, performance

#52 Build: Add test for rocksdb availability and minimum version
  Fulcrum.pro
  config.tests/rocksdb/main.cpp
  config.tests/rocksdb/test.pro
Labels: building

#53 Build: Add test for jemalloc and link it if found
  Fulcrum.pro
  config.tests/jemalloc/main.cpp
  config.tests/jemalloc/test.pro
Labels: building

#54 Docker: Remove jemalloc preload and use new config test instead
  contrib/docker/Dockerfile
Labels: packaging

#55 Build: Fix rocksdb test, c++17 has to be explicitly enabled
  config.tests/rocksdb/test.pro
Labels: building

#58 RPM: Use jemalloc + tweak
  contrib/rpm/fulcrum.spec
Labels: packaging
